package com.github.devapro.pttdroid.mvi

import kotlin.reflect.KClass

interface Reducer<ACTION : NEXT, STATE, NEXT : Any, EVENT> {

    val actionClass: KClass<ACTION>

    // Kotlin/Native requires a suspend function's @Throws list to include
    // CancellationException (or a supertype) explicitly — otherwise a cancelled coroutine's
    // exception would be indistinguishable from a real failure across the Kotlin/ObjC suspend
    // boundary. Harmless on the JVM: @Throws there only affects the generated bytecode's
    // declared checked exceptions for Java callers, none of which exist for this interface.
    // Found compiling for iosSimulatorArm64 (Phase 7a) — this was already wrong for a target this
    // repo could not previously build for at all.
    @Throws(ClassCastException::class, kotlin.coroutines.cancellation.CancellationException::class)
    suspend fun reduce(action: ACTION, state: STATE): Result<STATE, NEXT, EVENT?>

    infix fun <STATE, NEXT> STATE.to(that: NEXT?): Result<STATE, NEXT, EVENT> = Result(this, that)

    data class Result<out STATE, out NEXT_ACTION, out EVENT>(
        val state: STATE,
        val action: NEXT_ACTION? = null,
        val event: EVENT? = null
    )
}