import org.jetbrains.kotlin.gradle.dsl.JvmTarget

/**
 * `version.properties` (versionName/versionCode) and `relay.properties` (the default relay) are
 * parsed once, in `gradle/relay-defaults.gradle.kts`, and shared by every module that needs them
 * (`:app`, `:shared`, `:desktopApp`) — see that file for why, and for the exact parsing rules
 * (F-Droid builds a plain checkout with no Gradle properties set, so both files have to keep
 * working read directly off disk).
 */
apply(from = "$rootDir/gradle/relay-defaults.gradle.kts")

val appVersionName: String by extra
val appVersionCode: Int by extra
val defaultRelayHost: String by extra
val defaultRelayPort: Int by extra
val defaultRelayTls: Boolean by extra

plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.jetbrainsKotlinAndroid)
    alias(libs.plugins.jetbrainsKotlinCompose)
    alias(libs.plugins.jetbrainsKotlinSerialization)
    // Only for the `compose.components.resources` dependency below: :shared's Compose
    // Multiplatform `Res` accessor (StringResource/PluralStringResource) is generated by this
    // plugin, and :shared's own dependency on the resources library is `implementation`-scoped
    // so it does not reach :app transitively. :app is still a plain Android application module,
    // not a KMP one — this plugin is applied purely for the dependency accessor it provides.
    alias(libs.plugins.composeMultiplatform)
}

android {
    namespace = "com.github.devapro.pttdroid"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.github.devapro.pttdroid"
        minSdk = 24
        targetSdk = 36
        versionCode = appVersionCode
        versionName = appVersionName

        buildConfigField("String", "DEFAULT_RELAY_HOST", "\"$defaultRelayHost\"")
        buildConfigField("int", "DEFAULT_RELAY_PORT", "$defaultRelayPort")
        buildConfigField("boolean", "DEFAULT_RELAY_TLS", "$defaultRelayTls")

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
    }

    /**
     * Release signing, supplied by the environment so no key material is ever in the repository.
     *
     * Android will not install an update signed with a different key, so this key has to outlive
     * every release. It lives in CI secrets; see `docs/fdroid.md`.
     *
     * When the variables are absent the config is simply not created and `assembleRelease`
     * produces an unsigned APK — which is the right outcome for a local build, and which the
     * publishing workflow checks for rather than shipping by accident.
     */
    val keystorePath: String? = System.getenv("PTT_KEYSTORE_PATH")
    if (!keystorePath.isNullOrBlank()) {
        signingConfigs {
            create("release") {
                storeFile = file(keystorePath)
                storePassword = System.getenv("PTT_KEYSTORE_PASSWORD")
                keyAlias = System.getenv("PTT_KEY_ALIAS")
                keyPassword = System.getenv("PTT_KEY_PASSWORD")
                // minSdk is 24, so the v1 JAR signature nothing above API 23 reads is dead
                // weight; AGP drops it here regardless of what this flag says. v3 carries the
                // rotation proof, which matters for a key that has to outlive every release.
                enableV2Signing = true
                enableV3Signing = true
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfig = signingConfigs.findByName("release")
        }
    }

    /**
     * Keep the Play dependency-metadata blob out of the APK.
     *
     * It is an encrypted blob whose contents cannot be reproduced from source, which breaks
     * F-Droid's reproducible-build check, and it exists to report the dependency tree to Google
     * Play — a store this app is not on.
     */
    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    buildFeatures {
        compose = true
        buildConfig = true
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

dependencies {

    // :shared holds everything platform-independent (domain, MVI, the Compose UI, settings,
    // network) — see docs/architecture.md. PTTdroidApplication.onCreate() loads its Koin modules
    // alongside :app's own.
    implementation(project(":shared"))
    // Res.string.*/Res.plurals.* (generated in :shared) resolve to StringResource/
    // PluralStringResource; the accessor functions themselves (stringResource, getString,
    // pluralStringResource, getPluralString) live in this artifact, which :shared depends on
    // as `implementation` only, so :app needs its own copy on its compile classpath.
    implementation(compose.components.resources)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.lifecycle.service)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    implementation(libs.androidx.datastore.preferences)
    implementation(libs.androidx.glance.appwidget)
    implementation(libs.androidx.glance)
    implementation(libs.di.koin)
    implementation(libs.di.koin.androidx.compose)
    implementation(libs.network.ktor.core)
    implementation(libs.network.ktor.okhttp)
    implementation(libs.network.ktor.websockets)
    implementation(libs.network.ktor.server.cio)
    implementation(libs.network.ktor.server.websockets)
    implementation(libs.logs.timber)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.kotlinx.serialization.json)

    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.network.ktor.client.cio)
    testImplementation(libs.network.ktor.tls.certificates)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.ui.test.junit4)
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
}
